version: '2.1'

services:
  owncloud:
    container_name: owncloud
    image: rniesler/rpi-owncloud
    ports:
      - 443:443
    volumes:
      - /mnt/raid/Docker/Volumes/OwncloudConfig:/var/www/owncloud/config
      - /mnt/raid/OwncloudData:/var/www/owncloud/data
    depends_on:
      - ownclouddb
    restart: always
    mem_limit: 1000m
  ownclouddb:
    container_name: owncloud_db
    image: hypriot/rpi-mysql
    ports:
      - 3306:3306
    volumes:
      - /mnt/raid/Docker/Volumes/MySQL:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=initial
    restart: always
    mem_limit: 500m

networks:
  default:
    name: rnpinetwork
